pipeline {
    agent any
    stages {
        stage('静态检查') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('编译打包') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('单元测试') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('组件测试') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('功能测试') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('测试环境部署') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('性能测试') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('生产环境部署') {
            steps {
                bat 'mvn clean'
            }
        }
    }
}